[package]
name = "slickit-crust-python"
description = "SLICK Python crust — PyO3 bindings for slickit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "slick"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3.workspace = true
slickit = { workspace = true, features = ["manifest"] }
serde_json.workspace = true
